apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: devops-app-ingress

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
  - host: app.xwarhamx.ru

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: devops-app-service

            port:
              number: 80
